### PR TITLE
Fix/230609 fix other details

### PR DESCRIPTION
**Pull request by philipkcl**
https://github.com/culturesofknowledge/emlo-project/issues/228

### CODE REVIEW

**Comment by philipkcl** [comment]
Could you explain what and why should not add to `person_utils`
what is the problem of those code?
```
    for mmap in person.passive_relationships.all():
        display_name = recref_utils.get_recref_rel_desc(mmap, mmap.related, default_raw_value=True)
        result_map[display_name].append(
            get_recref_display_name(mmap.person)
        )
```
> should get_display_dict_other_details() not ouput HTML with links to the entities, so that it is possible to see information about the related entity?

I'm not sure about the question 
* `get_display_dict_other_details()` did not output HTML except data contain HTML.
* why do we need to link to related entity? the original system should have no such feature

**Comment by philipkcl** [comment]
`get_display_dict_other_details` is shared for csv and search page, that is not that sample and take time to create new version in search page only.
For the linking, User can link to related entity inside the form.

**Comment by J4bbi** [comment]
Okay, but what about also displaying passive relationships?

**Comment by J4bbi** [comment]
Under your implementation Alexander, William (ipersonid: 914112) shows an active relationship with Alexander, Jean (ipersonid: 914111). This is the parent relationship type.

image

When you look at the record for Alexander, Jean there is no relationship indicated, this is because they are passive.
image

If you include the passive relationships like in the code snippet I shared, you see the relationships Alexander, Jean has with two others.
image

**Comment by philipkcl** [comment]
Finally, I got what you meaning. 
Yes, passive _relationships is missing, updated PR

**Pull request merged**
